# coval_tracing.py — generated by `coval traces setup`
#
# This module configures OpenTelemetry tracing for Coval evaluation.
# Call setup_coval_tracing() once at startup, then set_simulation_id()
# when the Coval simulation ID arrives (typically via SIP header).
#
# Spans are buffered until set_simulation_id() is called, so no spans
# are lost even if tracing is initialized before the call connects.
#
# Span names must follow Coval conventions:
#   llm           — LLM inference spans
#   tts           — Text-to-speech spans
#   stt           — Speech-to-text spans
#   llm_tool_call — Tool/function call spans
#
# See: https://docs.coval.dev/traces

import logging
import os
from typing import Optional, Sequence

from opentelemetry import trace
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
from opentelemetry.sdk.resources import SERVICE_NAME, Resource
from opentelemetry.sdk.trace import ReadableSpan, Span, SpanProcessor, TracerProvider
from opentelemetry.sdk.trace.export import SimpleSpanProcessor, SpanExporter, SpanExportResult

logger = logging.getLogger("coval_tracing")

COVAL_API_KEY = os.environ.get("COVAL_API_KEY", "")
COVAL_TRACES_ENDPOINT = "https://api.coval.dev/v1/traces"

# Module-level reference so set_simulation_id() can reach the exporter.
_exporter: Optional["_DynamicCovalExporter"] = None

# ── Span renamer ─────────────────────────────────────────────────────────────
# Remaps span names from framework conventions to Coval conventions on start.

_SPAN_NAME_MAP = {
    "llm_request": "llm",
    "llm_request_run": "llm",
    "tts_request": "tts",
    "tts_request_run": "tts",
    "stt_request": "stt",
    "stt_request_run": "stt",
}


class _CovalSpanRenamer(SpanProcessor):
    """Renames spans on start to match Coval conventions."""

    def on_start(self, span: Span, parent_context=None) -> None:
        name = span.name
        if name in _SPAN_NAME_MAP:
            span._name = _SPAN_NAME_MAP[name]
        elif name.startswith("function_call"):
            span._name = "llm_tool_call"

    def on_end(self, span: ReadableSpan) -> None:
        pass

    def shutdown(self) -> None:
        pass

    def force_flush(self, timeout_millis: int = 30000) -> bool:
        return True


# ── Dynamic exporter ─────────────────────────────────────────────────────────

class _DynamicCovalExporter(SpanExporter):
    """Buffers spans until the Coval simulation ID is known.

    Call set_simulation_id() when the ID arrives (e.g. from a SIP header).
    All buffered spans are flushed immediately, and subsequent spans export
    in real time.
    """

    def __init__(self, api_key: str):
        self._api_key = api_key
        self._inner: Optional[OTLPSpanExporter] = None
        self._buffer: list[ReadableSpan] = []

    def reset(self) -> None:
        """Reset for a new call (if the agent handles multiple calls)."""
        if self._inner:
            self._inner.shutdown()
        self._inner = None
        self._buffer.clear()

    def activate(self, simulation_id: str) -> None:
        """Start exporting spans with the given simulation ID."""
        if self._inner:
            self._inner.shutdown()
        self._inner = OTLPSpanExporter(
            endpoint=COVAL_TRACES_ENDPOINT,
            headers={
                "x-api-key": self._api_key,
                "X-Simulation-Id": simulation_id,
            },
            timeout=30,
        )
        if self._buffer:
            logger.info("Flushing %d buffered spans to Coval", len(self._buffer))
            self._inner.export(self._buffer)
            self._buffer.clear()

    def export(self, spans: Sequence[ReadableSpan]) -> SpanExportResult:
        if self._inner:
            return self._inner.export(spans)
        self._buffer.extend(spans)
        return SpanExportResult.SUCCESS

    def force_flush(self, timeout_millis: int = 30000) -> bool:
        return self._inner.force_flush(timeout_millis) if self._inner else True

    def shutdown(self) -> None:
        if self._inner:
            self._inner.shutdown()


# ── Public API ───────────────────────────────────────────────────────────────

def setup_coval_tracing(service_name: str = "coval-agent") -> None:
    """Initialize OpenTelemetry tracing for Coval. Call once at startup.

    Spans are buffered until set_simulation_id() is called.
    If COVAL_API_KEY is not set, tracing is silently disabled.
    """
    global _exporter
    if not COVAL_API_KEY:
        logger.warning("COVAL_API_KEY not set — tracing disabled")
        return
    if _exporter is not None:
        _exporter.reset()
        logger.info("Coval tracing reset — waiting for simulation ID")
        return
    _exporter = _DynamicCovalExporter(api_key=COVAL_API_KEY)
    resource = Resource.create({SERVICE_NAME: service_name})
    provider = TracerProvider(resource=resource)
    provider.add_span_processor(_CovalSpanRenamer())
    provider.add_span_processor(SimpleSpanProcessor(_exporter))
    trace.set_tracer_provider(provider)
    logger.info("Coval tracing initialized — waiting for simulation ID")


def set_simulation_id(simulation_id: str) -> None:
    """Activate trace export with the given simulation ID.

    Typically called when the Coval simulation ID arrives via SIP header
    (X-Coval-Simulation-Id) or environment variable (COVAL_SIMULATION_ID).
    """
    if _exporter and simulation_id:
        _exporter.activate(simulation_id)
        logger.info("Coval tracing active for simulation_id=%s", simulation_id)


# ── LiveKit session instrumentation ──────────────────────────────────────────
# Call instrument_session(session) after AgentSession.start() to hook events
# that create Coval-compatible spans for STT, tool calls, and TTFB metrics.

def instrument_session(session) -> None:
    """Hook AgentSession events to create Coval trace spans.

    Must be called after session.start(). Hooks:
    - user_input_transcribed -> creates "stt" spans with transcript attribute
    - function_tools_executed -> creates "llm_tool_call" spans
    - metrics_collected -> creates spans with metrics.ttfb attribute
    """
    tracer = trace.get_tracer("coval.instrumentation")

    def _on_user_input_transcribed(event):
        if not getattr(event, "is_final", False):
            return
        with tracer.start_as_current_span("stt") as span:
            span.set_attribute("transcript", event.transcript or "")

    def _on_function_tools_executed(event):
        for call in getattr(event, "function_calls", []):
            with tracer.start_as_current_span("llm_tool_call") as span:
                span.set_attribute("function.name", getattr(call, "name", ""))
                span.set_attribute("tool_call_id", getattr(call, "call_id", ""))
                span.set_attribute("function.arguments", getattr(call, "arguments", ""))

    def _on_metrics_collected(event):
        metrics = getattr(event, "metrics", None)
        if metrics is None:
            return
        metrics_type = getattr(metrics, "type", "")
        ttfb = getattr(metrics, "ttfb", None)
        if ttfb is None:
            return
        if metrics_type == "llm_metrics":
            span_name = "llm"
        elif metrics_type == "stt_metrics":
            span_name = "stt"
        elif metrics_type == "tts_metrics":
            span_name = "tts"
        else:
            return
        with tracer.start_as_current_span(span_name) as span:
            span.set_attribute("metrics.ttfb", ttfb)

    session.on("user_input_transcribed", _on_user_input_transcribed)
    session.on("function_tools_executed", _on_function_tools_executed)
    session.on("metrics_collected", _on_metrics_collected)
    logger.info("Coval session instrumentation active")


# ── Utility functions for non-LiveKit frameworks ─────────────────────────────

def create_llm_span(input_text: str = "", model: str = "", **kwargs):
    """Create an LLM span. Use as a context manager: with create_llm_span(...) as span: ..."""
    tracer = trace.get_tracer("coval.instrumentation")
    span = tracer.start_span("llm")
    if input_text:
        span.set_attribute("input", input_text)
    if model:
        span.set_attribute("gen_ai.request.model", model)
    for k, v in kwargs.items():
        span.set_attribute(k, v)
    return trace.use_span(span, end_on_exit=True)


def create_stt_span(transcript: str = "", **kwargs):
    """Create an STT span. Use as a context manager."""
    tracer = trace.get_tracer("coval.instrumentation")
    span = tracer.start_span("stt")
    if transcript:
        span.set_attribute("transcript", transcript)
    for k, v in kwargs.items():
        span.set_attribute(k, v)
    return trace.use_span(span, end_on_exit=True)


def create_tts_span(**kwargs):
    """Create a TTS span. Use as a context manager."""
    tracer = trace.get_tracer("coval.instrumentation")
    span = tracer.start_span("tts")
    for k, v in kwargs.items():
        span.set_attribute(k, v)
    return trace.use_span(span, end_on_exit=True)


def create_tool_call_span(name: str = "", call_id: str = "", arguments: str = "", **kwargs):
    """Create a tool call span. Use as a context manager."""
    tracer = trace.get_tracer("coval.instrumentation")
    span = tracer.start_span("llm_tool_call")
    if name:
        span.set_attribute("function.name", name)
    if call_id:
        span.set_attribute("tool_call_id", call_id)
    if arguments:
        span.set_attribute("function.arguments", arguments)
    for k, v in kwargs.items():
        span.set_attribute(k, v)
    return trace.use_span(span, end_on_exit=True)
